// ============================================
// Seed Data - Demo data for the system
// ============================================

import type { User, Application, Franchise, Payment, Receipt, DriverProfile, Feedback, FeeConfig, Notification } from '../types';

const oneYearAgo = new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString();
const sixMonthsAgo = new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString();
const threeMonthsAgo = new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString();
const oneMonthAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
const oneYearFromNow = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString();
const sixMonthsFromNow = new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString();

export const seedUsers: User[] = [
  {
    id: 'admin-001',
    username: 'admin',
    password: 'admin123',
    role: 'admin',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'admin@baliuag.gov.ph',
    phone: '0917-123-4567',
    address: 'Municipal Hall, Baliuag, Bulacan',
    createdAt: oneYearAgo,
  },
  {
    id: 'user-001',
    username: 'jcruz',
    password: 'password123',
    role: 'operator',
    firstName: 'Juan',
    lastName: 'Cruz',
    middleName: 'Dela',
    email: 'jcruz@email.com',
    phone: '0918-234-5678',
    address: 'Brgy. Poblacion, Baliuag, Bulacan',
    createdAt: oneYearAgo,
  },
  {
    id: 'user-002',
    username: 'msantos',
    password: 'password123',
    role: 'operator',
    firstName: 'Marco',
    lastName: 'Santos',
    middleName: 'Reyes',
    email: 'msantos@email.com',
    phone: '0919-345-6789',
    address: 'Brgy. Tangos, Baliuag, Bulacan',
    createdAt: sixMonthsAgo,
  },
  {
    id: 'user-003',
    username: 'arivera',
    password: 'password123',
    role: 'operator',
    firstName: 'Ana',
    lastName: 'Rivera',
    email: 'arivera@email.com',
    phone: '0920-456-7890',
    address: 'Brgy. Sabang, Baliuag, Bulacan',
    createdAt: threeMonthsAgo,
  },
  {
    id: 'user-004',
    username: 'pgarcia',
    password: 'password123',
    role: 'operator',
    firstName: 'Pedro',
    lastName: 'Garcia',
    middleName: 'Lopez',
    email: 'pgarcia@email.com',
    phone: '0921-567-8901',
    address: 'Brgy. Tarcan, Baliuag, Bulacan',
    createdAt: oneMonthAgo,
  },
  {
    id: 'user-005',
    username: 'rdelacruz',
    password: 'password123',
    role: 'operator',
    firstName: 'Rosa',
    lastName: 'Dela Cruz',
    email: 'rdelacruz@email.com',
    phone: '0922-678-9012',
    address: 'Brgy. Pagala, Meycauayan, Bulacan',
    createdAt: oneWeekAgo,
  },
  {
    id: 'pass-001',
    username: 'mlopez',
    password: 'password123',
    role: 'passenger',
    firstName: 'Maria',
    lastName: 'Lopez',
    email: 'mlopez@email.com',
    phone: '0923-111-2222',
    address: 'Brgy. Poblacion, Baliuag, Bulacan',
    createdAt: sixMonthsAgo,
  },
  {
    id: 'pass-002',
    username: 'jreyes',
    password: 'password123',
    role: 'passenger',
    firstName: 'Jose',
    lastName: 'Reyes',
    email: 'jreyes@email.com',
    phone: '0924-333-4444',
    address: 'Brgy. Tangos, Baliuag, Bulacan',
    createdAt: oneMonthAgo,
  },
];

export const seedApplications: Application[] = [
  {
    id: 'app-001',
    applicantId: 'user-001',
    applicantName: 'Juan Dela Cruz',
    type: 'new',
    status: 'approved',
    residency: 'resident',
    vehicleMake: 'Honda',
    vehicleModel: 'TMX 125',
    plateNumber: 'MC-1234',
    motorNumber: 'HND-TMX-001234',
    chassisNumber: 'CHS-001234',
    vehicleColor: 'Blue',
    todaName: 'Poblacion TODA',
    routeArea: 'Poblacion - Market Route',
    documents: [
      { id: 'doc-001', name: "Driver's License", type: 'drivers_license', fileName: 'license_jcruz.pdf', uploadedAt: oneYearAgo, status: 'verified' },
      { id: 'doc-002', name: 'Community Tax Certificate', type: 'community_tax_cert', fileName: 'ctc_jcruz.pdf', uploadedAt: oneYearAgo, status: 'verified' },
      { id: 'doc-003', name: 'Deed of Sale', type: 'deed_of_sale', fileName: 'deed_jcruz.pdf', uploadedAt: oneYearAgo, status: 'verified' },
    ],
    baseFee: 500,
    latePenalty: 0,
    totalFee: 500,
    adminNotes: 'All documents verified. Application approved.',
    reviewedBy: 'admin-001',
    reviewedAt: oneYearAgo,
    submittedAt: oneYearAgo,
    updatedAt: oneYearAgo,
  },
  {
    id: 'app-002',
    applicantId: 'user-002',
    applicantName: 'Marco Reyes Santos',
    type: 'new',
    status: 'approved',
    residency: 'resident',
    vehicleMake: 'Yamaha',
    vehicleModel: 'YTX 125',
    plateNumber: 'MC-5678',
    motorNumber: 'YMH-YTX-005678',
    chassisNumber: 'CHS-005678',
    vehicleColor: 'Red',
    todaName: 'Tangos TODA',
    routeArea: 'Tangos - Public Market Route',
    documents: [
      { id: 'doc-004', name: "Driver's License", type: 'drivers_license', fileName: 'license_msantos.pdf', uploadedAt: sixMonthsAgo, status: 'verified' },
      { id: 'doc-005', name: 'Community Tax Certificate', type: 'community_tax_cert', fileName: 'ctc_msantos.pdf', uploadedAt: sixMonthsAgo, status: 'verified' },
      { id: 'doc-006', name: 'Deed of Sale', type: 'deed_of_sale', fileName: 'deed_msantos.pdf', uploadedAt: sixMonthsAgo, status: 'verified' },
    ],
    baseFee: 500,
    latePenalty: 0,
    totalFee: 500,
    adminNotes: 'Approved - all requirements met.',
    reviewedBy: 'admin-001',
    reviewedAt: sixMonthsAgo,
    submittedAt: sixMonthsAgo,
    updatedAt: sixMonthsAgo,
  },
  {
    id: 'app-003',
    applicantId: 'user-003',
    applicantName: 'Ana Rivera',
    type: 'new',
    status: 'under_review',
    residency: 'resident',
    vehicleMake: 'Suzuki',
    vehicleModel: 'Raider 150',
    plateNumber: 'MC-9012',
    motorNumber: 'SZK-RDR-009012',
    chassisNumber: 'CHS-009012',
    vehicleColor: 'Black',
    todaName: 'Sabang TODA',
    routeArea: 'Sabang - Town Center Route',
    documents: [
      { id: 'doc-007', name: "Driver's License", type: 'drivers_license', fileName: 'license_arivera.pdf', uploadedAt: threeMonthsAgo, status: 'uploaded' },
      { id: 'doc-008', name: 'Community Tax Certificate', type: 'community_tax_cert', fileName: 'ctc_arivera.pdf', uploadedAt: threeMonthsAgo, status: 'uploaded' },
      { id: 'doc-009', name: 'Deed of Sale', type: 'deed_of_sale', fileName: 'deed_arivera.pdf', uploadedAt: threeMonthsAgo, status: 'uploaded' },
    ],
    baseFee: 500,
    latePenalty: 0,
    totalFee: 500,
    submittedAt: threeMonthsAgo,
    updatedAt: oneMonthAgo,
  },
  {
    id: 'app-004',
    applicantId: 'user-004',
    applicantName: 'Pedro Lopez Garcia',
    type: 'new',
    status: 'pending',
    residency: 'resident',
    vehicleMake: 'Honda',
    vehicleModel: 'XRM 125',
    plateNumber: 'MC-3456',
    motorNumber: 'HND-XRM-003456',
    chassisNumber: 'CHS-003456',
    vehicleColor: 'White',
    todaName: 'Tarcan TODA',
    routeArea: 'Tarcan - Baliuag Public Market',
    documents: [
      { id: 'doc-010', name: "Driver's License", type: 'drivers_license', fileName: 'license_pgarcia.pdf', uploadedAt: oneMonthAgo, status: 'uploaded' },
      { id: 'doc-011', name: 'Community Tax Certificate', type: 'community_tax_cert', fileName: 'ctc_pgarcia.pdf', uploadedAt: oneMonthAgo, status: 'uploaded' },
    ],
    baseFee: 500,
    latePenalty: 0,
    totalFee: 500,
    submittedAt: oneMonthAgo,
    updatedAt: oneMonthAgo,
  },
  {
    id: 'app-005',
    applicantId: 'user-005',
    applicantName: 'Rosa Dela Cruz',
    type: 'new',
    status: 'pending',
    residency: 'non_resident',
    vehicleMake: 'Kawasaki',
    vehicleModel: 'CT 150',
    plateNumber: 'MC-7890',
    motorNumber: 'KWS-CT-007890',
    chassisNumber: 'CHS-007890',
    vehicleColor: 'Green',
    todaName: 'Pagala TODA',
    routeArea: 'Pagala - SM Baliuag Route',
    documents: [
      { id: 'doc-012', name: "Driver's License", type: 'drivers_license', fileName: 'license_rdelacruz.pdf', uploadedAt: oneWeekAgo, status: 'uploaded' },
      { id: 'doc-013', name: 'Community Tax Certificate', type: 'community_tax_cert', fileName: 'ctc_rdelacruz.pdf', uploadedAt: oneWeekAgo, status: 'uploaded' },
      { id: 'doc-014', name: 'Deed of Sale', type: 'deed_of_sale', fileName: 'deed_rdelacruz.pdf', uploadedAt: oneWeekAgo, status: 'uploaded' },
    ],
    baseFee: 1000,
    latePenalty: 0,
    totalFee: 1000,
    submittedAt: oneWeekAgo,
    updatedAt: oneWeekAgo,
  },
];

export const seedFranchises: Franchise[] = [
  {
    id: 'fran-001',
    applicationId: 'app-001',
    operatorId: 'user-001',
    operatorName: 'Juan Dela Cruz',
    vehicleMake: 'Honda',
    vehicleModel: 'TMX 125',
    plateNumber: 'MC-1234',
    motorNumber: 'HND-TMX-001234',
    chassisNumber: 'CHS-001234',
    vehicleColor: 'Blue',
    todaName: 'Poblacion TODA',
    routeArea: 'Poblacion - Market Route',
    residency: 'resident',
    status: 'active',
    issuedAt: oneYearAgo,
    expiresAt: oneYearFromNow,
    renewalDate: sixMonthsFromNow,
  },
  {
    id: 'fran-002',
    applicationId: 'app-002',
    operatorId: 'user-002',
    operatorName: 'Marco Reyes Santos',
    vehicleMake: 'Yamaha',
    vehicleModel: 'YTX 125',
    plateNumber: 'MC-5678',
    motorNumber: 'YMH-YTX-005678',
    chassisNumber: 'CHS-005678',
    vehicleColor: 'Red',
    todaName: 'Tangos TODA',
    routeArea: 'Tangos - Public Market Route',
    residency: 'resident',
    status: 'active',
    issuedAt: sixMonthsAgo,
    expiresAt: oneYearFromNow,
    renewalDate: sixMonthsFromNow,
  },
];

export const seedPayments: Payment[] = [
  {
    id: 'pay-001',
    applicationId: 'app-001',
    payerId: 'user-001',
    payerName: 'Juan Dela Cruz',
    amount: 500,
    baseFee: 500,
    latePenalty: 0,
    status: 'completed',
    paymentMethod: 'qr_code',
    referenceNumber: 'REF-2025-00001',
    paidAt: oneYearAgo,
    createdAt: oneYearAgo,
  },
  {
    id: 'pay-002',
    applicationId: 'app-002',
    payerId: 'user-002',
    payerName: 'Marco Reyes Santos',
    amount: 500,
    baseFee: 500,
    latePenalty: 0,
    status: 'completed',
    paymentMethod: 'qr_code',
    referenceNumber: 'REF-2025-00002',
    paidAt: sixMonthsAgo,
    createdAt: sixMonthsAgo,
  },
];

export const seedReceipts: Receipt[] = [
  {
    id: 'rcpt-001',
    paymentId: 'pay-001',
    applicationId: 'app-001',
    receiptNumber: 'OR-2025-00001',
    payerName: 'Juan Dela Cruz',
    amount: 500,
    description: 'New Franchise Registration Fee - Resident',
    issuedAt: oneYearAgo,
    issuedBy: 'System',
  },
  {
    id: 'rcpt-002',
    paymentId: 'pay-002',
    applicationId: 'app-002',
    receiptNumber: 'OR-2025-00002',
    payerName: 'Marco Reyes Santos',
    amount: 500,
    description: 'New Franchise Registration Fee - Resident',
    issuedAt: sixMonthsAgo,
    issuedBy: 'System',
  },
];

export const seedDrivers: DriverProfile[] = [
  {
    id: 'drv-001',
    userId: 'user-001',
    franchiseId: 'fran-001',
    firstName: 'Juan',
    lastName: 'Cruz',
    middleName: 'Dela',
    licenseNumber: 'N01-23-456789',
    licenseExpiry: oneYearFromNow,
    address: 'Brgy. Poblacion, Baliuag, Bulacan',
    phone: '0918-234-5678',
    email: 'jcruz@email.com',
    todaName: 'Poblacion TODA',
    routeArea: 'Poblacion - Market Route',
    plateNumber: 'MC-1234',
    status: 'active',
    authorizedAt: oneYearAgo,
    profilePhoto: '',
    averageRating: 4.5,
    totalTrips: 1247,
    registeredAt: oneYearAgo,
  },
  {
    id: 'drv-002',
    userId: 'user-002',
    franchiseId: 'fran-002',
    firstName: 'Marco',
    lastName: 'Santos',
    middleName: 'Reyes',
    licenseNumber: 'N02-34-567890',
    licenseExpiry: oneYearFromNow,
    address: 'Brgy. Tangos, Baliuag, Bulacan',
    phone: '0919-345-6789',
    email: 'msantos@email.com',
    todaName: 'Tangos TODA',
    routeArea: 'Tangos - Public Market Route',
    plateNumber: 'MC-5678',
    status: 'active',
    authorizedAt: sixMonthsAgo,
    profilePhoto: '',
    averageRating: 4.2,
    totalTrips: 834,
    registeredAt: sixMonthsAgo,
  },
];

export const seedFeedback: Feedback[] = [
  {
    id: 'fb-001',
    driverId: 'drv-001',
    driverName: 'Juan Dela Cruz',
    passengerName: 'Maria Lopez',
    rating: 5,
    comment: 'Very polite and safe driver. The tricycle was clean and well-maintained. Highly recommended!',
    category: 'service',
    status: 'reviewed',
    createdAt: oneMonthAgo,
    reviewedAt: oneWeekAgo,
  },
  {
    id: 'fb-002',
    driverId: 'drv-001',
    driverName: 'Juan Dela Cruz',
    passengerName: 'Roberto Garcia',
    rating: 4,
    comment: 'Good service overall. Arrived on time and was courteous.',
    category: 'punctuality',
    status: 'reviewed',
    createdAt: threeMonthsAgo,
    reviewedAt: oneMonthAgo,
  },
  {
    id: 'fb-003',
    driverId: 'drv-002',
    driverName: 'Marco Reyes Santos',
    passengerName: 'Elena Cruz',
    rating: 3,
    comment: 'The ride was okay but the tricycle could use some cleaning. Driver was friendly though.',
    category: 'cleanliness',
    status: 'pending',
    createdAt: oneWeekAgo,
  },
  {
    id: 'fb-004',
    driverId: 'drv-002',
    driverName: 'Marco Reyes Santos',
    passengerName: 'Jose Reyes',
    rating: 5,
    comment: 'Excellent driver! Very careful on the road and knew the fastest route.',
    category: 'safety',
    status: 'reviewed',
    createdAt: oneMonthAgo,
    reviewedAt: oneWeekAgo,
  },
];

export const seedFeeConfig: FeeConfig = {
  newRegistrationResident: 500,
  newRegistrationNonResident: 1000,
  renewalResident: 300,
  renewalNonResident: 600,
  latePenaltyPerMonth: 50,
  maxLatePenaltyMonths: 12,
};

export const seedNotifications: Notification[] = [
  {
    id: 'notif-001',
    userId: 'user-001',
    title: 'Franchise Active',
    message: 'Your franchise registration has been approved and is now active.',
    type: 'success',
    read: true,
    createdAt: oneYearAgo,
  },
  {
    id: 'notif-002',
    userId: 'user-003',
    title: 'Application Under Review',
    message: 'Your application is now being reviewed by LGU staff.',
    type: 'info',
    read: false,
    createdAt: oneMonthAgo,
  },
  {
    id: 'notif-003',
    userId: 'user-001',
    title: 'Renewal Reminder',
    message: 'Your franchise renewal date is approaching. Please prepare your documents.',
    type: 'warning',
    read: false,
    createdAt: oneWeekAgo,
  },
];

// TODA Routes in Baliuag
export const todaRoutes = [
  { name: 'Poblacion TODA', route: 'Poblacion - Market Route' },
  { name: 'Tangos TODA', route: 'Tangos - Public Market Route' },
  { name: 'Sabang TODA', route: 'Sabang - Town Center Route' },
  { name: 'Tarcan TODA', route: 'Tarcan - Baliuag Public Market' },
  { name: 'Pagala TODA', route: 'Pagala - SM Baliuag Route' },
  { name: 'Pinagbarilan TODA', route: 'Pinagbarilan - Municipal Hall Route' },
  { name: 'Tiaong TODA', route: 'Tiaong - New Market Route' },
  { name: 'Sta. Barbara TODA', route: 'Sta. Barbara - Town Proper Route' },
];
