// ============================================
// Seed Data - Demo data for Baliuag Franchise System
// ============================================

import type { User, Application, Franchise, Penalty, SMSNotification, FeeConfig } from '../types';

const oneYearAgo = new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString();
const sixMonthsAgo = new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString();
const oneMonthAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
const twoWeeksAgo = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString();
const threeDaysAgo = new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString();
const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();


const oneYearFromNow = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString();
const twoMonthsFromNow = new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString();
const fiveDaysFromNow = new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString();

export const seedUsers: User[] = [
  {
    id: 'user-admin-01',
    username: 'admin',
    password: 'admin123',
    role: 'admin',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'admin@baliuag.gov.ph',
    phone: '0917-123-4567',
    address: 'Baliuag Municipal Hall, Bulacan',
    createdAt: oneYearAgo,
  },
  {
    id: 'user-driver-01',
    username: 'driver',
    password: 'driver123',
    role: 'driver',
    firstName: 'Juan',
    lastName: 'Manaloto',
    middleName: 'Reyes',
    email: 'jmanaloto@gmail.com',
    phone: '0918-555-0101',
    address: 'Brgy. Poblacion, Baliuag, Bulacan',
    todaName: 'BASTODA (Baliuag Poblacion TODA)',
    createdAt: sixMonthsAgo,
  },
  {
    id: 'user-toda-01',
    username: 'todapres',
    password: 'toda123',
    role: 'toda_president',
    firstName: 'Ernesto',
    lastName: 'Santos',
    middleName: 'Cruz',
    email: 'president@bastoda.org',
    phone: '0919-888-0202',
    address: 'BASTODA Terminal, Brgy. Poblacion, Baliuag',
    todaName: 'BASTODA (Baliuag Poblacion TODA)',
    createdAt: oneYearAgo,
  },
  {
    id: 'user-operator-01',
    username: 'operator',
    password: 'operator123',
    role: 'operator',
    firstName: 'Juan',
    lastName: 'Cruz',
    middleName: 'Dela',
    email: 'jcruz@email.com',
    phone: '0920-777-0303',
    address: 'Brgy. Sabang, Baliuag, Bulacan',
    createdAt: oneYearAgo,
  },
  {
    id: 'user-driver-02',
    username: 'driver2',
    password: 'driver123',
    role: 'driver',
    firstName: 'Pedro',
    lastName: 'Penduko',
    email: 'ppenduko@email.com',
    phone: '0921-444-0404',
    address: 'Brgy. Tangos, Baliuag, Bulacan',
    todaName: 'SMTODA (Sabang Terminal TODA)',
    createdAt: oneMonthAgo,
  }
];

export const seedApplications: Application[] = [
  {
    id: 'APP-2026-001',
    applicantId: 'user-driver-01',
    applicantName: 'Juan Manaloto',
    applicantRole: 'driver',
    type: 'new',
    status: 'pending_toda_approval',
    driverName: 'Juan Manaloto',
    licenseNumber: 'N02-18-998234',
    vehicleMake: 'Honda',
    vehicleModel: 'TMX 125',
    plateNumber: '123-XYZ',
    motorNumber: 'ENG-994821',
    chassisNumber: 'CHS-881204',
    vehicleColor: 'Red / Metallic Chrome',
    todaName: 'BASTODA (Baliuag Poblacion TODA)',
    routeArea: 'Poblacion - Public Market - Plaza Naning',
    documents: [
      { id: 'doc-1', name: 'OR / CR (Vehicle Registration)', type: 'or_cr', fileName: 'or_cr_scanned.pdf', uploadedAt: threeDaysAgo, status: 'verified' },
      { id: 'doc-2', name: 'Barangay Clearance', type: 'barangay_clearance', fileName: 'brgy_clearance.pdf', uploadedAt: threeDaysAgo, status: 'verified' },
      { id: 'doc-3', name: 'Driver License', type: 'drivers_license', fileName: 'driver_license.jpg', uploadedAt: threeDaysAgo, status: 'verified' },
      { id: 'doc-4', name: 'TODA Certification', type: 'toda_cert', fileName: 'toda_membership.pdf', uploadedAt: threeDaysAgo, status: 'verified' },
      { id: 'doc-5', name: '2x2 ID Photo', type: 'id_photo', fileName: 'id_photo.png', uploadedAt: threeDaysAgo, status: 'verified' },
    ],
    inspection: {
      id: 'insp-001',
      applicationId: 'APP-2026-001',
      engineNumber: 'ENG-994821',
      chassisNumber: 'CHS-881204',
      engineVerified: true,
      chassisVerified: true,
      inspectorName: 'Insp. Rodolfo Gonzales (City Stenciling Office)',
      inspectedAt: yesterday,
      status: 'passed',
      notes: 'Engine and Chassis numbers match original documents perfectly. Stenciling verified.',
    },
    treasurerPayment: {
      paid: true,
      amount: 450,
      orNumber: 'OR-TREAS-88192',
      paidAt: yesterday,
      paymentMethod: 'cash',
    },
    todaApproval: {
      approvedBy: 'user-toda-01',
      approvedByName: 'Cap. Ernesto Santos',
      todaName: 'BASTODA (Baliuag Poblacion TODA)',
      approvedAt: '',
      routeFeePaid: false,
      membershipFeePaid: false,
      routeFeeAmount: 500,
      membershipFeeAmount: 300,
    },
    baseFee: 450,
    todaFee: 800,
    latePenalty: 0,
    totalFee: 1250,
    submittedAt: threeDaysAgo,
    updatedAt: yesterday,
  },
  {
    id: 'APP-2026-002',
    applicantId: 'user-operator-01',
    applicantName: 'Juan Cruz',
    applicantRole: 'operator',
    type: 'renewal',
    status: 'approved',
    driverName: 'Juan Manaloto',
    licenseNumber: 'N02-18-998234',
    vehicleMake: 'Kawasaki',
    vehicleModel: 'Barako II',
    plateNumber: '456-ABC',
    motorNumber: 'ENG-334112',
    chassisNumber: 'CHS-776231',
    vehicleColor: 'Blue / Silver',
    todaName: 'BASTODA (Baliuag Poblacion TODA)',
    routeArea: 'Poblacion - Sabang - DRT Highway',
    documents: [
      { id: 'doc-10', name: 'OR / CR (Vehicle Registration)', type: 'or_cr', fileName: 'or_cr_2026.pdf', uploadedAt: oneMonthAgo, status: 'verified' },
      { id: 'doc-11', name: 'Barangay Clearance', type: 'barangay_clearance', fileName: 'brgy_clearance.pdf', uploadedAt: oneMonthAgo, status: 'verified' },
      { id: 'doc-12', name: 'Driver License', type: 'drivers_license', fileName: 'license.jpg', uploadedAt: oneMonthAgo, status: 'verified' },
    ],
    inspection: {
      id: 'insp-002',
      applicationId: 'APP-2026-002',
      engineNumber: 'ENG-334112',
      chassisNumber: 'CHS-776231',
      engineVerified: true,
      chassisVerified: true,
      inspectorName: 'Insp. Rodolfo Gonzales',
      inspectedAt: twoWeeksAgo,
      status: 'passed',
      notes: 'Inspection cleared.',
    },
    treasurerPayment: {
      paid: true,
      amount: 450,
      orNumber: 'OR-TREAS-77123',
      paidAt: twoWeeksAgo,
      paymentMethod: 'gcash',
    },
    todaApproval: {
      approvedBy: 'user-toda-01',
      approvedByName: 'Cap. Ernesto Santos',
      todaName: 'BASTODA (Baliuag Poblacion TODA)',
      approvedAt: twoWeeksAgo,
      routeFeePaid: true,
      membershipFeePaid: true,
      routeFeeAmount: 500,
      membershipFeeAmount: 300,
      orNumber: 'TODA-OR-9002',
      remarks: 'Route membership active. Cleared for MTOP renewal.',
    },
    baseFee: 450,
    todaFee: 800,
    latePenalty: 0,
    totalFee: 1250,
    adminNotes: 'MTOP Franchise renewed successfully for 2026-2027.',
    reviewedBy: 'Maria Garcia (Admin)',
    reviewedAt: twoWeeksAgo,
    mtopNumber: 'MTOP-2026-0891',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=MTOP-2026-0891-JUAN-MANALOTO',
    submittedAt: oneMonthAgo,
    updatedAt: twoWeeksAgo,
  },
  {
    id: 'APP-2026-003',
    applicantId: 'user-driver-02',
    applicantName: 'Pedro Penduko',
    applicantRole: 'driver',
    type: 'new',
    status: 'pending_inspection',
    driverName: 'Pedro Penduko',
    licenseNumber: 'N01-19-445892',
    vehicleMake: 'Yamaha',
    vehicleModel: 'YTX 125',
    plateNumber: '789-DEF',
    motorNumber: 'ENG-112093',
    chassisNumber: 'CHS-443910',
    vehicleColor: 'Black / Yellow',
    todaName: 'SMTODA (Sabang Terminal TODA)',
    routeArea: 'Sabang - SM City Baliwag - Tarcan',
    documents: [
      { id: 'doc-20', name: 'OR / CR (Vehicle Registration)', type: 'or_cr', fileName: 'yamaha_orcr.pdf', uploadedAt: yesterday, status: 'uploaded' },
      { id: 'doc-21', name: 'Barangay Clearance', type: 'barangay_clearance', fileName: 'clearance_pedro.pdf', uploadedAt: yesterday, status: 'uploaded' },
      { id: 'doc-22', name: 'Driver License', type: 'drivers_license', fileName: 'pedro_license.jpg', uploadedAt: yesterday, status: 'uploaded' },
      { id: 'doc-23', name: 'TODA Certification', type: 'toda_cert', fileName: 'smtoda_cert.pdf', uploadedAt: yesterday, status: 'uploaded' },
      { id: 'doc-24', name: '2x2 ID Photo', type: 'id_photo', fileName: 'pedro_2x2.png', uploadedAt: yesterday, status: 'uploaded' },
    ],
    baseFee: 450,
    todaFee: 800,
    latePenalty: 0,
    totalFee: 1250,
    submittedAt: yesterday,
    updatedAt: yesterday,
  }
];

export const seedFranchises: Franchise[] = [
  {
    id: 'FRAN-2026-001',
    mtopNumber: 'MTOP-2026-0891',
    applicationId: 'APP-2026-002',
    operatorId: 'user-operator-01',
    operatorName: 'Juan Cruz',
    driverId: 'user-driver-01',
    driverName: 'Juan Manaloto',
    vehicleMake: 'Kawasaki',
    vehicleModel: 'Barako II',
    plateNumber: '456-ABC',
    motorNumber: 'ENG-334112',
    chassisNumber: 'CHS-776231',
    vehicleColor: 'Blue / Silver',
    todaName: 'BASTODA (Baliuag Poblacion TODA)',
    routeArea: 'Poblacion - Sabang - DRT Highway',
    status: 'active',
    issuedAt: twoWeeksAgo,
    expiresAt: oneYearFromNow,
    renewalDate: twoMonthsFromNow,
    qrCodeData: 'BALIUAG-MTOP-0891|PLATE:456-ABC|DRIVER:JUAN MANALOTO|STATUS:ACTIVE',
  },
  {
    id: 'FRAN-2025-044',
    mtopNumber: 'MTOP-2025-0441',
    applicationId: 'APP-2025-998',
    operatorId: 'user-operator-01',
    operatorName: 'Juan Cruz',
    driverId: 'user-driver-02',
    driverName: 'Pedro Penduko',
    vehicleMake: 'Suzuki',
    vehicleModel: 'GD 110',
    plateNumber: '992-XYZ',
    motorNumber: 'ENG-001923',
    chassisNumber: 'CHS-554109',
    vehicleColor: 'Red',
    todaName: 'SMTODA (Sabang Terminal TODA)',
    routeArea: 'Sabang - SM City Baliwag',
    status: 'expired',
    issuedAt: oneYearAgo,
    expiresAt: yesterday,
    renewalDate: yesterday,
    qrCodeData: 'BALIUAG-MTOP-0441|PLATE:992-XYZ|DRIVER:PEDRO PENDUKO|STATUS:EXPIRED',
  }
];

export const seedPenalties: Penalty[] = [
  {
    id: 'PEN-2026-001',
    driverId: 'user-driver-01',
    driverName: 'Juan Manaloto',
    plateNumber: '123-XYZ',
    todaName: 'BASTODA (Baliuag Poblacion TODA)',
    violationType: 'Out of Route Operation',
    amount: 500,
    status: 'unpaid',
    issuedDate: twoWeeksAgo,
    dueDate: fiveDaysFromNow,
    remarks: 'Operated outside designated TODA boundary at DRT Highway without special permit.',
    issuedBy: 'Traffic Enforcer Officer R. Santos',
  },
  {
    id: 'PEN-2026-002',
    driverId: 'user-driver-02',
    driverName: 'Pedro Penduko',
    plateNumber: '992-XYZ',
    todaName: 'SMTODA (Sabang Terminal TODA)',
    violationType: 'Expired MTOP',
    amount: 1000,
    status: 'unpaid',
    issuedDate: yesterday,
    dueDate: fiveDaysFromNow,
    remarks: 'Driving with expired MTOP permit (Expired yesterday).',
    issuedBy: 'Admin Penalty Management System',
  }
];

export const seedSMSNotifications: SMSNotification[] = [
  {
    id: 'sms-001',
    userId: 'user-operator-01',
    recipientPhone: '0920-777-0303',
    title: 'Franchise Renewal Reminder',
    message: 'PAALALA: Ang inyong MTOP Franchise (Plate: 992-XYZ) ay mag-eexpire na. Mangyaring magsumite ng renewal bago ang nakatakdang petsa.',
    type: 'renewal_reminder',
    sentAt: threeDaysAgo,
    read: false,
  },
  {
    id: 'sms-002',
    userId: 'user-driver-01',
    recipientPhone: '0918-555-0101',
    title: 'Penalty Violation Notice',
    message: 'ABISO: Mayroon kayong na-record na penalty para sa Out of Route Operation (PHP 500.00). Mangyaring bayaran sa Treasurer’s Office bago mag-expire.',
    type: 'penalty_alert',
    sentAt: twoWeeksAgo,
    read: true,
  },
  {
    id: 'sms-003',
    userId: 'user-driver-01',
    recipientPhone: '0918-555-0101',
    title: 'Stenciling & Inspection Cleared',
    message: 'MAHALAGANG ABISO: Ang inyong makina at chassis stenciling ay APRUBADO na! Maari na kayong magbayad sa Treasurer’s Office at TODA President.',
    type: 'status_update',
    sentAt: yesterday,
    read: false,
  }
];

export const seedFeeConfig: FeeConfig = {
  mtopBaseFee: 450,
  todaRouteFee: 500,
  todaMembershipFee: 300,
  stencilingFee: 150,
  latePenaltyPerMonth: 200,
};
